### ISSUE TITLE
README ?

### ISSUE THREAD

**Issue by LarsImNetz** [fluffynuts/polymer-ts-scratch#1]
Hi,

Would be nice to have a simple readme with some texyt, how to use such code.

JM2C
Kind regards
Lars

**Comment by fluffynuts** [comment]
Hi

I'm not sure what to write in a README with respect to "how to use"? This is a small Polymer project using TypeScript, so the code just serves as examples of how to get some stuff done in Polymer with TypeScript. I think the only thing I could really add would be "open the code in a text editor and hack away" (:

Unless you have something more useful in mind? I'm not being funny -- just not sure what would be useful on top of the existing README
